// filepath: /Users/andrewshyshkin/Documents/work/terraria clone/js/blocks.js
// Block size in pixels
var BLOCK_SIZE = 32

// Block types - made global for access from other files
var BLOCK_TYPES = {
	AIR: 0,
	DIRT: 1,
	STONE: 2,
	GRASS: 3,
	WOOD: 4,
	LEAVES: 5,
	COAL_ORE: 6,
	IRON_ORE: 7,
	GOLD_ORE: 8,
	TORCH: 9,
	ROPE: 10,
	DIAMOND_ORE: 11,
	RUBY_ORE: 12,
	SAPPHIRE_ORE: 13,
	EMERALD_ORE: 14,
	COPPER_ORE: 15,
	GEL: 50,
	TITANIUM_ORE: 16,
	PLATINUM_ORE: 17,
	OBSIDIAN_ORE: 18,
	MITHRIL_ORE: 19,
	WOOD_PLATFORM: 60,
	WOODEN_DOOR: 61,
	CHAIR: 62,
	TABLE: 63,
	CHAIN: 64,
	WORKBENCH: 70,
	FURNACE: 71,
	ANVIL: 72,
	// Переработанные руды
	IRON_BAR: 20,
	GOLD_BAR: 21,
	COPPER_BAR: 22,
	TITANIUM_BAR: 23,
	PLATINUM_BAR: 24,
	OBSIDIAN_BAR: 25,
	MITHRIL_BAR: 26,
	// Инструменты
	WOODEN_PICKAXE: 30,
	WOODEN_AXE: 31,
	STONE_PICKAXE: 32,
	STONE_AXE: 33,
	COPPER_PICKAXE: 34,
	COPPER_AXE: 35,
	IRON_PICKAXE: 36,
	IRON_AXE: 37,
	GOLD_PICKAXE: 38,
	GOLD_AXE: 39,
	DIAMOND_PICKAXE: 40,
	DIAMOND_AXE: 41,
	TITANIUM_PICKAXE: 42,
	TITANIUM_AXE: 43,
	PLATINUM_PICKAXE: 44,
	PLATINUM_AXE: 45,
	OBSIDIAN_PICKAXE: 46,
	OBSIDIAN_AXE: 47,
	MITHRIL_PICKAXE: 48,
	MITHRIL_AXE: 49,
}

// Обновите свойства блоков, добавив правильные значения для свойства lightEmission

// Блок с определением BLOCKS - made global for access from other files
var BLOCKS = {
	[BLOCK_TYPES.AIR]: {
		name: 'Air',
		solid: false,
		texture: null,
		breakable: false,
		lightEmission: 0,
	},
	[BLOCK_TYPES.DIRT]: {
		name: 'Dirt',
		solid: true,
		texture: '#8B4513',
		breakable: true,
		hardness: 1,
		lightEmission: 0,
	},
	[BLOCK_TYPES.STONE]: {
		name: 'Stone',
		solid: true,
		texture: '#808080',
		breakable: true,
		hardness: 1, // Reduced from 2 to 1 for beginners
		lightEmission: 0,
	},
	[BLOCK_TYPES.GRASS]: {
		name: 'Grass',
		solid: true,
		texture: '#567D46',
		breakable: true,
		hardness: 1,
		lightEmission: 0,
	},
	[BLOCK_TYPES.WOOD]: {
		name: 'Wood',
		solid: true,
		texture: '#8B4513',
		breakable: true,
		hardness: 2,
		lightEmission: 0,
	},
	[BLOCK_TYPES.LEAVES]: {
		name: 'Leaves',
		solid: true,
		texture: '#228B22',
		breakable: true,
		hardness: 1,
		lightEmission: 0,
	},
	[BLOCK_TYPES.COAL_ORE]: {
		name: 'Coal Ore',
		solid: true,
		texture: '#454545',
		breakable: true,
		hardness: 3,
		lightEmission: 0,
	},
	[BLOCK_TYPES.IRON_ORE]: {
		name: 'Iron Ore',
		solid: true,
		texture: '#CD7F32',
		breakable: true,
		hardness: 4,
		lightEmission: 0,
	},
	[BLOCK_TYPES.GOLD_ORE]: {
		name: 'Gold Ore',
		solid: true,
		texture: '#FFD700',
		breakable: true,
		hardness: 5,
		lightEmission: 0,
	},
	[BLOCK_TYPES.TORCH]: {
		name: 'Torch',
		solid: false,
		texture: '#FFA500',
		breakable: true,
		hardness: 1,
		lightEmission: 4, // Увеличиваем яркость факелов
	},
	[BLOCK_TYPES.ROPE]: {
		name: 'Rope',
		solid: false,
		climbable: true,
		texture: '#A0522D',
		breakable: true,
		hardness: 1,
		lightEmission: 0,
	},
	[BLOCK_TYPES.DIAMOND_ORE]: {
		name: 'Diamond Ore',
		solid: true,
		texture: '#B9F2FF',
		breakable: true,
		hardness: 7,
		lightEmission: 0,
	},
	[BLOCK_TYPES.RUBY_ORE]: {
		name: 'Ruby Ore',
		solid: true,
		texture: '#E0115F',
		breakable: true,
		hardness: 6,
		lightEmission: 0,
	},
	[BLOCK_TYPES.SAPPHIRE_ORE]: {
		name: 'Sapphire Ore',
		solid: true,
		texture: '#0F52BA',
		breakable: true,
		hardness: 6,
		lightEmission: 0,
	},
	[BLOCK_TYPES.EMERALD_ORE]: {
		name: 'Emerald Ore',
		solid: true,
		texture: '#50C878',
		breakable: true,
		hardness: 6,
		lightEmission: 0,
	},
	[BLOCK_TYPES.COPPER_ORE]: {
		name: 'Copper Ore',
		solid: true,
		texture: '#B87333',
		breakable: true,
		hardness: 3,
		lightEmission: 0,
	},
	[BLOCK_TYPES.TITANIUM_ORE]: {
		name: 'Titanium Ore',
		solid: true,
		texture: '#A0A0A0',
		breakable: true,
		hardness: 6,
		lightEmission: 0,
	},
	[BLOCK_TYPES.PLATINUM_ORE]: {
		name: 'Platinum Ore',
		solid: true,
		texture: '#E5E4E2',
		breakable: true,
		hardness: 7,
		lightEmission: 0,
	},
	[BLOCK_TYPES.OBSIDIAN_ORE]: {
		name: 'Obsidian Ore',
		solid: true,
		texture: '#3A3A3A',
		breakable: true,
		hardness: 8,
		lightEmission: 0,
	},
	[BLOCK_TYPES.MITHRIL_ORE]: {
		name: 'Mithril Ore',
		solid: true,
		texture: '#4A86E8',
		breakable: true,
		hardness: 9,
		lightEmission: 0,
	},
	[BLOCK_TYPES.IRON_BAR]: {
		name: 'Iron Bar',
		solid: true,
		texture: '#A9A9A9',
		breakable: true,
		hardness: 3,
		lightEmission: 0,
	},
	[BLOCK_TYPES.GOLD_BAR]: {
		name: 'Gold Bar',
		solid: true,
		texture: '#FFD700',
		breakable: true,
		hardness: 3,
		lightEmission: 0,
	},
	[BLOCK_TYPES.COPPER_BAR]: {
		name: 'Copper Bar',
		solid: true,
		texture: '#B87333',
		breakable: true,
		hardness: 3,
		lightEmission: 0,
	},
	[BLOCK_TYPES.TITANIUM_BAR]: {
		name: 'Titanium Bar',
		solid: true,
		texture: '#878787',
		breakable: true,
		hardness: 3,
		lightEmission: 0,
	},
	[BLOCK_TYPES.PLATINUM_BAR]: {
		name: 'Platinum Bar',
		solid: true,
		texture: '#E5E4E2',
		breakable: true,
		hardness: 3,
		lightEmission: 0,
	},
	[BLOCK_TYPES.OBSIDIAN_BAR]: {
		name: 'Obsidian Bar',
		solid: true,
		texture: '#3A3A3A',
		breakable: true,
		hardness: 4,
		lightEmission: 0,
	},
	[BLOCK_TYPES.MITHRIL_BAR]: {
		name: 'Mithril Bar',
		solid: true,
		texture: '#4A86E8',
		breakable: true,
		hardness: 4,
		lightEmission: 0,
	},
	[BLOCK_TYPES.WOODEN_PICKAXE]: {
		name: 'Wooden Pickaxe',
		solid: false,
		texture: '#8B4513',
		breakable: false,
		toolType: 'pickaxe',
		miningPower: 1,
		durability: 50,
	},
	[BLOCK_TYPES.WOODEN_AXE]: {
		name: 'Wooden Axe',
		solid: false,
		texture: '#8B4513',
		breakable: false,
		toolType: 'axe',
		miningPower: 1,
		durability: 50,
	},
	[BLOCK_TYPES.STONE_PICKAXE]: {
		name: 'Stone Pickaxe',
		solid: false,
		texture: '#808080',
		breakable: false,
		toolType: 'pickaxe',
		miningPower: 2,
		durability: 100,
	},
	[BLOCK_TYPES.STONE_AXE]: {
		name: 'Stone Axe',
		solid: false,
		texture: '#808080',
		breakable: false,
		toolType: 'axe',
		miningPower: 2,
		durability: 100,
	},
	[BLOCK_TYPES.COPPER_PICKAXE]: {
		name: 'Copper Pickaxe',
		solid: false,
		texture: '#B87333',
		breakable: false,
		toolType: 'pickaxe',
		miningPower: 3,
		durability: 150,
	},
	[BLOCK_TYPES.COPPER_AXE]: {
		name: 'Copper Axe',
		solid: false,
		texture: '#B87333',
		breakable: false,
		toolType: 'axe',
		miningPower: 3,
		durability: 150,
	},
	[BLOCK_TYPES.IRON_PICKAXE]: {
		name: 'Iron Pickaxe',
		solid: false,
		texture: '#A9A9A9',
		breakable: false,
		toolType: 'pickaxe',
		miningPower: 4,
		durability: 250,
	},
	[BLOCK_TYPES.IRON_AXE]: {
		name: 'Iron Axe',
		solid: false,
		texture: '#A9A9A9',
		breakable: false,
		toolType: 'axe',
		miningPower: 4,
		durability: 250,
	},
	[BLOCK_TYPES.GOLD_PICKAXE]: {
		name: 'Gold Pickaxe',
		solid: false,
		texture: '#FFD700',
		breakable: false,
		toolType: 'pickaxe',
		miningPower: 5,
		durability: 300,
	},
	[BLOCK_TYPES.GOLD_AXE]: {
		name: 'Gold Axe',
		solid: false,
		texture: '#FFD700',
		breakable: false,
		toolType: 'axe',
		miningPower: 5,
		durability: 300,
	},
	[BLOCK_TYPES.DIAMOND_PICKAXE]: {
		name: 'Diamond Pickaxe',
		solid: false,
		texture: '#B9F2FF',
		breakable: false,
		toolType: 'pickaxe',
		miningPower: 7,
		durability: 500,
	},
	[BLOCK_TYPES.DIAMOND_AXE]: {
		name: 'Diamond Axe',
		solid: false,
		texture: '#B9F2FF',
		breakable: false,
		toolType: 'axe',
		miningPower: 7,
		durability: 500,
	},
	[BLOCK_TYPES.TITANIUM_PICKAXE]: {
		name: 'Titanium Pickaxe',
		solid: false,
		texture: '#A0A0A0',
		breakable: false,
		toolType: 'pickaxe',
		miningPower: 8,
		durability: 600,
	},
	[BLOCK_TYPES.TITANIUM_AXE]: {
		name: 'Titanium Axe',
		solid: false,
		texture: '#A0A0A0',
		breakable: false,
		toolType: 'axe',
		miningPower: 8,
		durability: 600,
	},
	[BLOCK_TYPES.PLATINUM_PICKAXE]: {
		name: 'Platinum Pickaxe',
		solid: false,
		texture: '#E5E4E2',
		breakable: false,
		toolType: 'pickaxe',
		miningPower: 9,
		durability: 700,
	},
	[BLOCK_TYPES.PLATINUM_AXE]: {
		name: 'Platinum Axe',
		solid: false,
		texture: '#E5E4E2',
		breakable: false,
		toolType: 'axe',
		miningPower: 9,
		durability: 700,
	},
	[BLOCK_TYPES.OBSIDIAN_PICKAXE]: {
		name: 'Obsidian Pickaxe',
		solid: false,
		texture: '#3A3A3A',
		breakable: false,
		toolType: 'pickaxe',
		miningPower: 10,
		durability: 800,
	},
	[BLOCK_TYPES.OBSIDIAN_AXE]: {
		name: 'Obsidian Axe',
		solid: false,
		texture: '#3A3A3A',
		breakable: false,
		toolType: 'axe',
		miningPower: 10,
		durability: 800,
	},
	[BLOCK_TYPES.MITHRIL_PICKAXE]: {
		name: 'Mithril Pickaxe',
		solid: false,
		texture: '#4A86E8',
		breakable: false,
		toolType: 'pickaxe',
		miningPower: 11,
		durability: 1000,
	},
	[BLOCK_TYPES.MITHRIL_AXE]: {
		name: 'Mithril Axe',
		solid: false,
		texture: '#4A86E8',
		breakable: false,
		toolType: 'axe',
		miningPower: 11,
		durability: 1000,
	},
	[BLOCK_TYPES.GEL]: {
		name: 'Slime Gel',
		solid: false,
		texture: '#32CD32', // Lime green
		breakable: true,
		hardness: 1,
		lightEmission: 0,
	},
	[BLOCK_TYPES.WOOD_PLATFORM]: {
		name: 'Wooden Platform',
		solid: false, // Players can jump through platforms
		texture: '#8B4513', // SaddleBrown
		breakable: true,
		hardness: 1,
		lightEmission: 0,
		isPlatform: true, // Special property for platforms
	},
	[BLOCK_TYPES.WOODEN_DOOR]: {
		name: 'Wooden Door',
		solid: true,
		texture: '#A0522D', // Sienna
		breakable: true,
		hardness: 2,
		lightEmission: 0,
		isDoor: true,
	},
	[BLOCK_TYPES.CHAIR]: {
		name: 'Wooden Chair',
		solid: true,
		texture: '#CD853F', // Peru
		breakable: true,
		hardness: 1,
		lightEmission: 0,
	},
	[BLOCK_TYPES.TABLE]: {
		name: 'Wooden Table',
		solid: true,
		texture: '#D2691E', // Chocolate
		breakable: true,
		hardness: 1,
		lightEmission: 0,
	},
	[BLOCK_TYPES.CHAIN]: {
		name: 'Chain',
		solid: false,
		texture: '#C0C0C0', // Silver
		breakable: true,
		hardness: 2,
		lightEmission: 0,
	},
	[BLOCK_TYPES.WORKBENCH]: {
		name: 'Workbench',
		solid: true,
		texture: '#8B4513', // SaddleBrown
		breakable: true,
		hardness: 2,
		lightEmission: 0,
		isCraftingStation: true,
		stationType: window.CRAFTING_STATIONS.WORKBENCH,
	},
	[BLOCK_TYPES.FURNACE]: {
		name: 'Furnace',
		solid: true,
		texture: '#696969', // DimGray
		breakable: true,
		hardness: 3,
		lightEmission: 3, // Emits some light
		isCraftingStation: true,
		stationType: window.CRAFTING_STATIONS.FURNACE,
	},
	[BLOCK_TYPES.ANVIL]: {
		name: 'Anvil',
		solid: true,
		texture: '#708090', // SlateGray
		breakable: true,
		hardness: 3,
		lightEmission: 0,
		isCraftingStation: true,
		stationType: window.CRAFTING_STATIONS.ANVIL,
	},
}

// Item textures - would be images in a full implementation - made global for access from other files
var ITEM_TEXTURES = {
	[BLOCK_TYPES.DIRT]: '#8B4513',
	[BLOCK_TYPES.STONE]: '#808080',
	[BLOCK_TYPES.GRASS]: '#567D46',
	[BLOCK_TYPES.WOOD]: '#8B4513',
	[BLOCK_TYPES.LEAVES]: '#228B22',
	[BLOCK_TYPES.COAL_ORE]: '#454545',
	[BLOCK_TYPES.IRON_ORE]: '#CD7F32',
	[BLOCK_TYPES.GOLD_ORE]: '#FFD700',
	[BLOCK_TYPES.TORCH]: '#FFA500',
	[BLOCK_TYPES.ROPE]: '#A0522D',
	[BLOCK_TYPES.DIAMOND_ORE]: '#B9F2FF',
	[BLOCK_TYPES.RUBY_ORE]: '#E0115F',
	[BLOCK_TYPES.SAPPHIRE_ORE]: '#0F52BA',
	[BLOCK_TYPES.EMERALD_ORE]: '#50C878',
	[BLOCK_TYPES.COPPER_ORE]: '#B87333',
	[BLOCK_TYPES.TITANIUM_ORE]: '#A0A0A0',
	[BLOCK_TYPES.PLATINUM_ORE]: '#E5E4E2',
	[BLOCK_TYPES.OBSIDIAN_ORE]: '#3A3A3A',
	[BLOCK_TYPES.MITHRIL_ORE]: '#4A86E8',

	// Metal bars
	[BLOCK_TYPES.IRON_BAR]: '#A9A9A9',
	[BLOCK_TYPES.GOLD_BAR]: '#FFD700',
	[BLOCK_TYPES.COPPER_BAR]: '#B87333',
	[BLOCK_TYPES.TITANIUM_BAR]: '#878787',
	[BLOCK_TYPES.PLATINUM_BAR]: '#E5E4E2',
	[BLOCK_TYPES.OBSIDIAN_BAR]: '#3A3A3A',
	[BLOCK_TYPES.MITHRIL_BAR]: '#4A86E8',

	// Tools
	[BLOCK_TYPES.WOODEN_PICKAXE]: '#8B4513',
	[BLOCK_TYPES.WOODEN_AXE]: '#8B4513',
	[BLOCK_TYPES.STONE_PICKAXE]: '#808080',
	[BLOCK_TYPES.STONE_AXE]: '#808080',
	[BLOCK_TYPES.COPPER_PICKAXE]: '#B87333',
	[BLOCK_TYPES.COPPER_AXE]: '#B87333',
	[BLOCK_TYPES.IRON_PICKAXE]: '#A9A9A9',
	[BLOCK_TYPES.IRON_AXE]: '#A9A9A9',
	[BLOCK_TYPES.GOLD_PICKAXE]: '#FFD700',
	[BLOCK_TYPES.GOLD_AXE]: '#FFD700',
	[BLOCK_TYPES.DIAMOND_PICKAXE]: '#B9F2FF',
	[BLOCK_TYPES.DIAMOND_AXE]: '#B9F2FF',
	[BLOCK_TYPES.TITANIUM_PICKAXE]: '#A0A0A0',
	[BLOCK_TYPES.TITANIUM_AXE]: '#A0A0A0',
	[BLOCK_TYPES.PLATINUM_PICKAXE]: '#E5E4E2',
	[BLOCK_TYPES.PLATINUM_AXE]: '#E5E4E2',
	[BLOCK_TYPES.OBSIDIAN_PICKAXE]: '#3A3A3A',
	[BLOCK_TYPES.OBSIDIAN_AXE]: '#3A3A3A',
	[BLOCK_TYPES.MITHRIL_PICKAXE]: '#4A86E8',
	[BLOCK_TYPES.MITHRIL_AXE]: '#4A86E8',

	// New blocks & items
	[BLOCK_TYPES.WOOD_PLATFORM]: '#8B4513',
	[BLOCK_TYPES.WOODEN_DOOR]: '#A0522D',
	[BLOCK_TYPES.CHAIR]: '#CD853F',
	[BLOCK_TYPES.TABLE]: '#D2691E',
	[BLOCK_TYPES.CHAIN]: '#C0C0C0',
	[BLOCK_TYPES.WORKBENCH]: '#8B4513',
	[BLOCK_TYPES.FURNACE]: '#696969',
	[BLOCK_TYPES.ANVIL]: '#708090',
}

// Wall types - made global for access from renderer.js
var WALL_TYPES = {
	NONE: 0,
	DIRT: 1,
	STONE: 2,
	CAVE: 3,
}

// Wall definitions - made global for access from renderer.js
var WALLS = {
	[WALL_TYPES.NONE]: {
		name: 'None',
		texture: null,
	},
	[WALL_TYPES.DIRT]: {
		name: 'Dirt Wall',
		texture: '#654321', // Темно-коричневый
	},
	[WALL_TYPES.STONE]: {
		name: 'Stone Wall',
		texture: '#555555', // Темно-серый
	},
	[WALL_TYPES.CAVE]: {
		name: 'Cave Wall',
		texture: '#333333', // Очень темно-серый
	},
}
